In [23]:
import torch
import numpy as np

a = torch.rand(3,3)-0.5-0.5
b = a.numpy()

In [24]:
print(b)

[[-0.37095565 -0.71836054 -0.17438436]
 [-0.79157996 -0.90981066 -0.3019892 ]
 [-0.557912   -0.57866704 -0.91544175]]


In [25]:
import torch.nn.functional as F
import torch.nn as nn
c = F.relu(a)
print(c)
d= c.numpy()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [26]:
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
average = d[np.nonzero(d)].mean()
print(average)

nan


/home/hoyin/anaconda3/envs/solaris2/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice.
  """Entry point for launching an IPython kernel.
/home/hoyin/anaconda3/envs/solaris2/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)


In [28]:
(0.45018226+0.1657353+0.36326998+0.12874544)/4

0.276983245

In [30]:
for i in range (0,10) :
    if i < 2 : 
        print("0")
    elif 5>i>=2 : 
        print("1")
    else :
        print("2")
        

0
0
1
1
1
2
2
2
2
2
